version: "3.8"

services:
  qr-generator:
    image: registry.gitlab.com/wovera/qr-generator:latest
    ports:
      - "3030:3030"
    environment:
      - NODE_ENV=production
      - PORT=3030
    restart: unless-stopped
    container_name: qr-generator-app
